name: Google BigQuery Chainlink EA
description: Get any data from Google BigQuery
node_identifier: bigquery-cl-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: Google BigQuery
    url: https://cloud.google.com/
parameters:
  - query
  - row
  - column
