name:
description:
node_identifier: bigquery-cl-ea
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: GoogleBigQuery
    url: https://cloud.google.com/
parameters:
  - query
  - row
  - column
